### PR TITLE
Updated the error message for RangeError

### PR DESCRIPTION
**Pull request by sharifmamun**
This pull request is based on RangeError message is actually wrong #285 issue. Thanks!

### CODE REVIEW

**Comment by sharifmamun** [comment]
@wyuenho Please have a look into this simple pull request. Thanks!

**Comment by wyuenho** [comment]
Thanks! Can you provide a test?

**Comment by wyuenho** [comment]
I'll merge this now, it would be better if you could provide a test in a separate PR. Thanks a lot.

**Comment by sharifmamun** [comment]
@wyuenho is there any existing test for this particular exception?

**Comment by sharifmamun** [comment]
@wyuenho  I didn't hear back from you

**Pull request merged**
